### ISSUE TITLE
New object: "seesaw" to replace "attached bar"

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#112]
The attached bar object is confusing to users: it is birch, so it can move. but it doesn't because it only rotates. 

@lspacenl came up with the idea of using a seesaw, like
  * https://openclipart.org/detail/215388/seesaw-coloured 
but then of course in 2-D.

Actions:
 * [x] create the graphic
 * [x] create the object
 * [x] find all levels that contain the 'attached bar' or something similar like e.g. "contraption 1"
 * [x] replace them and test play again
 * [ ] run regression and see it passes.

**Comment by Wuzzy2** [comment]
Good one, because what I did in my levels was kind of a hack, hehe.

**Comment by kaa-ching** [comment]
commit 6cdab09 adds some basic graphic.

**Comment by kaa-ching** [comment]
I've now created two objects: RotatingBar and SeesawSmall.
They're different - the seesaw will return to a horizontal position.

**Comment by kaa-ching** [comment]
And regression is clean. yay. done!

**Comment by lspacenl** [comment]
what makes the seesaw return to the horizontal?
and why?

Met vriendelijke groet,

Peter van Ginneken

Never underestimate the bandwidth of a station wagon
<https://mail.google.com/wiki/Station_wagon> full of tapes hurtling down
the highway. —Tanenbaum, Andrew S.
<https://mail.google.com/wiki/Andrew_S._Tanenbaum> (1996). *Computer
Networks*. New Jersey: Prentice-Hall. p. 83.

2016-03-12 18:09 GMT+01:00 Klaas van Gend <notifications@github.com>:

**Comment by kaa-ching** [comment]
center of gravity below the pivot point.
