### ISSUE TITLE
Transfer ownership of tbe to an organization and setup a proper team

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#114]
Post milestone B, I want to revisit the project structure.

Right now, two people have commit rights whereas we have 6 regular contributors.
In a personal github account, which kaa-ching is now, I can have multiple collaborators, that each have all the rights kaa-ching has. Which is too many for e.g. @lspacenl or @amarsman to feel comfortable.

If we turn TBE over to an "organization", we can set up a team and have each member get permissions that he/she/we are comfortable with. See https://help.github.com/articles/repository-permission-levels-for-an-organization/

@DjSlash @glixx @Wuzzy2 @lspacenl @amarsman - I'd like to hear your comments, please!

**Comment by Wuzzy2** [comment]
I don't care. But if it helps getting work done …

**Comment by glixx** [comment]
Any additional permissions are nice.

**Comment by DjSlash** [comment]
When put in an organization, we can benefit from several things. Better to do that sooner than later. One thing to remember to do is changing the DNS again that reflects this change.

**Comment by kaa-ching** [comment]
For now assigning @DjSlash, to be implemented around Feb 20, i.e. well in time before the MilestoneB release.

**Comment by lspacenl** [comment]
Sounds like a plan.
I don't know in which time zone everybody is but i think that, seeing as
there are only six of that it should be feasible to get everybody online at
once and have some kind of group discussion.

Maybe this means that I finally get to do something more than be a
soundboard for ideas to bounced off.

Lspace

Met vriendelijke groet,

Peter van Ginneken

Never underestimate the bandwidth of a station wagon
<https://mail.google.com/wiki/Station_wagon> full of tapes hurtling down
the highway. —Tanenbaum, Andrew S.
<https://mail.google.com/wiki/Andrew_S._Tanenbaum> (1996). *Computer
Networks*. New Jersey: Prentice-Hall. p. 83.

2016-02-01 0:16 GMT+01:00 Klaas van Gend <notifications@github.com>:

**Comment by DjSlash** [comment]
A group discussion about what exactly and why can't that be done here in the issuetracker?

**Comment by kaa-ching** [comment]
Sounds like people are indeed discussing on several levels. Let's first move to a github organization. That will allow us to have multiple people in the project, assign roles and such. *Then* let's discuss how to communicate - is github's issue tracker enough (I don't think so), or what extras do we want.

**Comment by amarsman** [comment]
I agree @kaa-ching, let's do it step by step what already can be done and then it becomes clear if there's need for discussion. I would like to have a possibility to be able to communicate with others without having to create a ticket for every little question I have: be able to see that somebody is online and ask a question in a small group: IRC, whatsapp, Skype, forum, ...

**Comment by lspacenl** [comment]
Agreed but that would also imply that there is somebody who can take a
decision on any such questions because otherwise how are we gonna keep
track.

Met vriendelijke groet,

Peter van Ginneken

Never underestimate the bandwidth of a station wagon
<https://mail.google.com/wiki/Station_wagon> full of tapes hurtling down
the highway. —Tanenbaum, Andrew S.
<https://mail.google.com/wiki/Andrew_S._Tanenbaum> (1996). *Computer
Networks*. New Jersey: Prentice-Hall. p. 83.

2016-02-12 5:13 GMT+01:00 Aschwin Marsman <notifications@github.com>:

**Comment by DjSlash** [comment]
Transferred the repo to the new organization and invited everyone there. GH-pages already updated, DNS change has been requested. So that's done and now we can talk about other features for the organization. @kaa-ching created #149 for that one.

Closing this one.
