### ISSUE TITLE
Default names for toolbox items

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#120]
I noticed that the level file format forces you to explicitly specify a name for toolbox items. It seems you can leave it out, but then the game just does not show any name in the toolbox. :-(

I think it is a bit inconvenient and also bad design.
It leads to inconsistent/redundant/almost identical strings which is an issue for translation:

E.g. is it “Bowling Pin”, “bowling pin”, “Bowling pin”, or just “Pin”? Translators basically translate the same string. Also, things get annoying if you ever want to rename any item. Etc.

So I suggest for toolbox items, it should be possible to leave out the name. If the name is missing, the game will simply just just look up the object type in the object element and apply its name.
I think this is perfectly sensible since in >90% of cases the default name is just fine.

In the rare case the user wants to set a custom name, he/she can still set one explicitly, and of course the explicit name should take precedence.

**Comment by kaa-ching** [comment]
Totally agree. Thanks for the observation.

Actions:
 * [ ] fix the toolboxitemgroup to look for the name in more than one place
 * [ ] fix the levels to not include a default string

**Comment by kaa-ching** [comment]
done.
