### ISSUE TITLE
Player can “skip” solved levels

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#135]
You can mark any level as “skipped” even if it was previously solved.
If you do this, the level appears as “skipped” in the level list.

You can skip a level both in the “File” menu as well in the failure dialog when you lose (“Fail - retry?”).

I think the skip button should just be disabled in this case.

Revision: 678985f06f63c7003aa5a03e086332f0cd13b3c1

**Comment by kaa-ching** [comment]
Even if the level was previously solved, I think the "skip" button has its use - maybe a user decides to not solve the level at all. Skip will bring him to the next unsolved level.

So I prefer to keep the button active, but we definitely shouldn't corrupt the saved information.
