### ISSUE TITLE
“Continue” and “Select” buttons don't work while simulation is still running

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#136]
If you have completed a level and the “Congratulations!” dialog pops up, in the first few seconds the continue and level select buttons are useless. If you click them, the dialog just pops up another time. Also, the simulation still runs in the background for a few seconds (I guess this is intentional).

If you click it again, probably the dialog just pops up another time.

I have figured out that the dialog pops up again only while the simulation is still running in the background. As soon as it has been automatically paused after some seconds (for some reason) you can finally click the buttons and continue.

678985f06f63c7003aa5a03e086332f0cd13b3c1

Edit: I noticed something new: The “Continue” button *works* if you have some open (neither skipped nor done) level in the list. But the normal level selection button still behaves incorrectly. So it seems this bug also depends on whether you have done or skipped all levels.

**Comment by kaa-ching** [comment]
Somehow, the whole simulation code turned into a big mess. Several of the tickets (e.g. #78) are related to this. I'd better fix it correctly this time.

**Comment by kaa-ching** [comment]
fixed in the NewControls branch.
