### ISSUE TITLE
Aborting language selection makes language menu show multiple “selected” languages

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#146]
If you select a different language in the language menu, but then abort by clicking “No” on the dialog that pops up, the checkbox of the new language will be checked, along with the current language. So you have 2 checked languages in the language menu.

Revision: 0bb55229e71528ef148ff0dd2decbd8aa7f4be6d

PS: Shouldn't it be radio buttons instead of checkboxes, anyways?

**Comment by kaa-ching** [comment]
Unfortunately, there is no radio button for menu items...

**Comment by Wuzzy2** [comment]
Not to sound rude, but ever heard of `QActionGroup`? :P
https://doc.qt.io/qt-5/qactiongroup.html

**Comment by kaa-ching** [comment]
That's a great suggestion, I'll implement it!
