### ISSUE TITLE
Object cloning does not work anymore

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#153]
I am not sure if you noticed it, but the cloning feature does not work anymore in the Level Creator. If I click the clone button (after making a selection, of course), nothing happens.

b6067f70214b561bfc73bf567540a06d8ee51fe2

**Comment by kaa-ching** [comment]
I'll investigate.

**Comment by kaa-ching** [comment]
**** t=819: ERROR: on_action_Clone_triggered() for outdated object...
