### ISSUE TITLE
Level reset button does not work anymore

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#155]
How to reproduce:

* Start any level regularly
* Place some elements
* Click on the info icon and then click on reset and confirm

Result: Nothing is reset.

Tested on d7ea2a203b32ef5ded12cb3f6444f3f16825b432.

**Comment by kaa-ching** [comment]
Will be addressed as part of the rewrite of the GameControls.

**Comment by kaa-ching** [comment]
commit b33f0491ea85412c6405bfa0548dcc21fb146a50 fixes this.
