### ISSUE TITLE
Bad level: Extreme Tux Racer

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#156]
Extreme Tux Racer doesn't seem to work anymore as intended. The soccer ball does not seem to have enough energy to go to the bowling ball after bouncing from the spring. Unless I place it directly above the bowling ball (but this does not seem to be the intended solution).

d7ea2a203b32ef5ded12cb3f6444f3f16825b432
- [ ] replace the sleeping penguin with a SleepingPingus
- [ ] get rid of the zzz and penguin images
- [x] make the trapdoor work again, or use a different mechanism
- [ ] make the pingus goal on the bottom left, requiring the user to put a spring on the bottom right.

**Comment by kaa-ching** [comment]
Indeed.

**Comment by Wuzzy2** [comment]
Fixed it! By increasing SpringConstant to 640.
I also added an obstacle to get rid of the shortcut.

I did not replace the penguin with a Pingus object, as Pingus behaves too differently.
