### ISSUE TITLE
SeeSawSmall: Minor PivotPoint issues

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#159]
The new `SeeSawSmall` object does not rotate cleanly around that red center point. You clearly see this effect on the default 3×2 level size. So the PivotPoint of this should be tweaked a bit, I guess.

Also, the middle point visibly rotates with the rest, revealing the object as one single image. Luckily, this is kinda subtle. A cheap solution would be to make the middle circle of an uniform color.

**Comment by kaa-ching** [comment]
Agreed. See:
[seesawtest.zip](https://github.com/the-butterfly-effect/tbe/files/176785/seesawtest.zip)

**Comment by kaa-ching** [comment]
to prove it, you also need to adjust the center, so here's a new test file:

[seesawtest.zip](https://github.com/the-butterfly-effect/tbe/files/176830/seesawtest.zip)
