### ISSUE TITLE
Descriptions of custom objects are not translated

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#165]
It seems that descriptions of custom objects or custom tooltips are not translated, even if a translation is available. It does not matter whether the object is in the toolbox.

Example: Styrofoam blocks in the styrofoam level (`draft/styrofoam.xml`) in German. German translation has a translation, but it is not used. Seems to affect any other custom tooltips as well.

Revision: 12caa482f7cc547fedfde2c082c6aa5731c74dbb

**Comment by kaa-ching** [comment]
done.
