### ISSUE TITLE
Level quality assurance

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#167]
I propose some guidelines for a quality assurance of levels. This proposal is made out of several parts:

* Strong preference to making resources globally available instead of storing them in level directories
* New directory structure
* Defined quality requirements for levels considered “finished”

Proposed new directories in `levels`: I propse three directories in which all levels designed for playing are stored:

* `draft`: WIP levels which are not playable yet or have serious gameplay or graphical issues. Can change radically at any time
* `needs-polish`: Solvable and has proper goal text but has some minor issues, mostly graphical (caused by level itself, not by the engine). Also, a `needs-polish` level should be expected to not change significantly (esp. in gameplay)
* `finished`: Solvable and highly polished. High quality requirements, can be presented in `levels.xml` and probably the 1.0 release without embarrassing ourselves. ;-). Requirements:
    * Solvable
    * Unique name
    * Proper goal description. Succinct and to the point. Story-telling goes to post-it notes
    * No customized object is allowed if a standard object would have been appropriate as well. For example, no using `RectObject` with wood texture since `Floor` does the same thing.
    * Appropriate scene size
    * All object descriptions/tooltips must be correct, if a tooltip is present
    * Custom non-trivial objects must have tooltips. Reuse existing texts to be nice to translators.
    * Post-it note is optional, but if present, all text must fit into the box
    * No graphical issues or oddities (caused by the level)
    * For levels supposed to be difficult: No easy shortcuts should be possible. Must be decided on a case-on-case basis
    * Correct spelling and grammar
    * (Add your own requiremnets here if you have more ideas)

Also, merge everything in `99luft`, `angry`, `elce09`, `jumpingjack`, `picnic` and move them into one of the three directories above.

All shared resources (image files etc.) should be removed from level folders and instead be made available globally. IMO it is a bit messy to put the level resources in the level directory and many resources scream to be re-used anyways. Only justifiable exception may be draft and test levels.
But normally, only the level XML files should be in the folders to keep things clean.

Levels in `finished` should generally go into `levels.xml`. Levels in `needs-polish` *may* go into `level.xml`, needs to be decided on a case-by-case basis. Levels from other directories should not be included.

Here's the process of creating a new level under this new system:

* Save new levels into `draft`, including custom images if you're lazy
* If the level is in a playable state, move it either to `needs-polish` or directly to `finished` if it meets the requirements (important!)
* Polish the level and fix the remaining issues
* If you consider the level finished, do one final check and then move it into `finished`
* Custom resources of finished levels should be made available globally
* If the level is good, add it to `levels.xml`
* Later on: If any level in `finished` must be changed for any reason, ideally it should also be checked again before committing to avoid regressions. If the check fails, fix the problems, then commit. If this is not possible or you are too lazy, either don't commit or move the level back to `needs-polish`.

I post this issue for discussion first, before doing anything. Also, I think, if implemented, the images should be dealt with first, then comes the directory restructuring.

**Comment by kaa-ching** [comment]
yes, please :smile:

**Comment by Wuzzy2** [comment]
I have started working on this.

**Comment by Wuzzy2** [comment]
The QA requirements have been established, so I close this issue now.
A follow-up issue for polishing a bunch of levels has been created: https://github.com/the-butterfly-effect/tbe/issues/254

Other QA discussions should be created as new issues.
