### ISSUE TITLE
Goal text of Sorting 5 is not translated

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#168]
For some reason, the goal text of Sorting 5 is not translated or can not be translated.

In Transifex, I found the string “Throw all the balls into these slots, from left to right:” but the bullet point list which comes after that is missing, so maybe there's a problem with the “string-collecting scripts”. I don't know.

**Comment by kaa-ching** [comment]
Indeed, this is currently wrong. I hope @glixx (who originally wrote that script) can fix it - scripting of that level is beyond my pay grade...

**Comment by glixx** [comment]
Script works only for strings, which are written in one line.

**Comment by Wuzzy2** [comment]
Fixed by #170.
