### ISSUE TITLE
Some default object properties are not displayed correctly in object properties

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#169]
Some default object properties are not displayed correctly in the object properties list. For instance, if the object “factory” says the default bounciness is X, this is not correctly displayed in the properties list.

Examples:

* Wall
    * Bounciness should be 0.05 but is displayed as 0.3
    * Mass should be 0 but is displayed as empty string
* Hammer
    * Bounciness should be 0 but is displayed as 0.3
    * Friction should be 0 but is displayed as empty string

I haven't tested this deeply enough and I don't know how many objects are affected.

**Comment by kaa-ching** [comment]
I still have to complete that dialog :unamused: it's part of #66.
But thanks for pointing out this detail - I might have otherwise not noticed it.

**Comment by kaa-ching** [comment]
Commit 878384a solves part of this issue

**Comment by kaa-ching** [comment]
BTW: "Mass is empty string" is correct. If Mass is empty string, it is also considered zero but the object will be absolutely static - it's modelled differently and will never move.

**Comment by kaa-ching** [comment]
I think this ticket is complete.
