### ISSUE TITLE
Simplify using the pie menu

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#174]
Here's a suggestion, probably for later versions.

Currently, the pie menu works like this:
- Click on object to open pie menu
- Click on desired button
- If this button was not the move button, it will move to the center
- Click on the desired button _once again_ to actually activate the action

IMO this “moving into the center” thing is pointless, it is just an additional click and it is not even useful for anything. It just slows down interaction.

Suggestions to simplify the pie menu:
- No button is in the center, everything is around the center and stays there
- No “moving into the center” animation
- Clicking on object reveals the pie menu
- Clicking on any button on the pie menu immediately takes effect
- Dragging the object should work as before

**Comment by kaa-ching** [comment]
@amarsman and @lspacenl already suggested this as well

**Comment by kaa-ching** [comment]
By now, I'm inclined to add a Milestone C, just for UI polishing

**Comment by amarsman** [comment]
Yesterday at hacker space TkkrLab in Eschede people played TBE and had similar problems with the way you have to interact with objects. From one person I got the suggestion to look at InkScape, according to him they have similar issues to solve.

**Comment by kaa-ching** [comment]
PieMenu is gone. closing.
