### ISSUE TITLE
ugly: message loading en_US failed

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#184]
```
**** t=928: entry bool Singleton::Translator::init()
**** t=928: going to set locale 'en_US'
***  t=928: Singleton::Translator::setLanguage for locale 'en_US'
**   t=928: Attemp: load translator from tbe_en_US
**   t=928:    ... fail
**   t=928: Attemp: load translator from ./tbe_en_US
**   t=928:    ... fail
**   t=928: Attemp: load translator from /home/klaas/Programming/tbe-github-master/usr/games/../share/games/tbe/i18n/tbe_en_US
**   t=928:    ... fail
**** t=928: NOTE: translator for TBE is empty
***  t=928: NOTE: translator for Qt itself is empty
```

Note that the output is totally valid though. But I don't like that it actually tries to load the translator - it's the built-in one. Just adding one more if statement...

**Comment by amarsman** [comment]
Isn't it the case that we write the text strings in English but that we are not native speakers it could very well be that those texts need to be improved? In that case you probably don't want to change the text in the source code as that would imply that you have to update all the translations. Or is that the way you want to work? You could always sync the texts back to the source code at any time if you want to.

**Comment by kaa-ching** [comment]
That's the way it works. The source code is en_US, everything else follows the source code. That's why there is a 2-week "string freeze" after I declare the code 'done'. During "string freeze", only code changes (bug fixes!) that do not modify strings are allowed.
