### ISSUE TITLE
Add i18n to splash screen

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#185]
Usually, the splash screen won't be visible for long.
But it is not translated, it only shows the English name of the game.
Should we fix that?

**Comment by amarsman** [comment]
No, I don't think that translating the name of the game can help us, it should be named always the butterfly effect with optionally the native language name as a subtitle. People need to search for the butterfly effect package, if they search for "het vlindereffect" (dutch) in their software install system they won't find the game. Proposal: reject this issue.

**Comment by kaa-ching** [comment]
I'm going to resolve this by putting a message above the image. That message can be translated.
![splash-with-i18n](https://cloud.githubusercontent.com/assets/4249656/14403294/fc6765f4-fe51-11e5-8ec6-da0f6292c781.png)

**Comment by kaa-ching** [comment]
Oops, committed on the NewControls branch.
