### ISSUE TITLE
STRING FREEZE, complete all translations

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#187]
As of April 10, we're in string freeze.

Action List:
 * [x] complete all tickets for the milestone that can have string changes
 * [x] generate new translation files
 * [x] upload translation files to Transifex
 * [x] announce string freeze - to TBE and Transifex
 * [x] fix bugs without affecting strings
 * [x] build release candidates
 * [x] test release candidates
 * [x] download fixed strings
 * [x] rebuild release packages
 * [x] release

**Comment by kaa-ching** [comment]
commit 90d00d7 handles the second and third items.

**Comment by lspacenl** [comment]
Dutch translation on transifex is now at 100%

**Comment by amarsman** [comment]
Can we already download and commit the current status? That way it's easier to test the translation and we can see how far we are from complete. Do we have a minimal set of languages that should be 100% translated before release?

**Comment by kaa-ching** [comment]
I do not have requirements for completeness at this point.

I will upload the finished translations to github today.

**Comment by kaa-ching** [comment]
Will do new packaging on Monday. We're almost a month late now...

**Comment by kaa-ching** [comment]
All packages are now present.
I've run sanity checks on the Windows build and it appears to work as expected...
