### ISSUE TITLE
first screen is always pixelated

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#189]
When you start TBE, the first screen's images are always rendered like the window is in 640x480 or so. Only when you go to the next level, you'll get the high-quality images.

**Comment by Wuzzy2** [comment]
Yes, I know this issue and it has been there for a while. I have known it for a long time but apparently I always forgot to report it. :/

It is not only at the program start, it also seems to matter in which resolution you start a level with. If you start a level at low res, then you just need to maximize the window and everything is very pixelated until you start another level or reset the current one.

**Comment by kaa-ching** [comment]
It would be interesting to know for how long exactly, because that would help in pinning down when it went wrong. Up till now, I was mostly building/testing on a 1366x768 screen. In that case it doesn't show so bad. On the Full HD screen I now use, the issue is clearly visible. Oh well, my bad. Let's start bisecting.

**Comment by kaa-ching** [comment]
Hmm, this issue is really old :unamused: 

Let's just attack it heads on, then.

**Comment by kaa-ching** [comment]
After a lot of research, I realized that there are two problems:
 * the game first starts in "windowed" mode, only then maximized
 * when a level is loaded, the graphics are scaled to the then-settings and never rescaled.

So, current behavior is a combination of the above.
This is also shown when a level is started windowed and then is maximized by the user: it won't redraw its graphics, so the level will remain pixelated.

I see two solutions:
 * wait loading the level until MainWindow has been resized. 1 line fix. but doesn't solve the underlying issues.
 * implement a resize event for ViewWorld and all ViewObjects. This is quite a heavy fix.

**Comment by amarsman** [comment]
Let's split this:

1. one line fix in milestone B
2. real fix in milestone C

**Comment by kaa-ching** [comment]
agreed.

**Comment by kaa-ching** [comment]
*This* issue doesn't happen in the QML UI :smile:
