### ISSUE TITLE
Pingu image is completely broken

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#192]
Just start any level with pingus in it.
You'll notice the pingus now look _really_ weird at the level start. If they start walking, you will see pingu images all over the place!
Tested in 90d00d7a9ee69cbf03e1b278aeb1435ca5dc56d2 on GNU/Linux.

I take the freedom to assign this to milestone B because this is pretty serious IMO.

**Comment by kaa-ching** [comment]
See #190
