### ISSUE TITLE
Minor string “overhang” in toolbox item description

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#193]
The description texts for the toolbox items seems to often go over the “border” and doesn't look pretty. It seems to happen quite often for the last line in the text.
Try the level “The Pit”. For some reason, the effect is more noticable in German, but it happens for English, too.
90d00d7a9ee69cbf03e1b278aeb1435ca5dc56d2

**Comment by kaa-ching** [comment]
Can you supply a screenshot, I don't seem to recognize the issue, not even with "The Pit" in German...

**Comment by Wuzzy2** [comment]
Level The Pit in German version:

* https://i.imgur.com/qTg1X6v.png
* https://i.imgur.com/HvJavi8.png

**Comment by Wuzzy2** [comment]
Not fixed in fa4289fee2ee5f4c159a0d2b46e794282800fa4c:
https://i.imgur.com/mxKNTCd.png
https://i.imgur.com/XAofgh4.png

**Comment by kaa-ching** [comment]
Not a problem in the new toolbox anymore.
