### ISSUE TITLE
Pie menu appears displaced or doesn't appear at all for large objects

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#194]
90d00d7a9ee69cbf03e1b278aeb1435ca5dc56d2

Try to play Sorting 5.
Take some floors, scale them up horizontally and now try to access their pie menu with left click. It doesn't seem to work anymore. Either the pie menu is displaced or it is not visible at all, making the level unplayable.

**Comment by kaa-ching** [comment]
There's a red herring in PieMenu.cpp, lines 83-85:
```
	// Quite a convoluted way to figure out the scaling transformation that the QGraphicsWidget parent of ours does
	// TODO/FIXME: I have no clue where that 0.5 comes from, but it appears to work reasonably well...
	theActionIconScaling = 0.5*mapFromScene(QRectF(0,0,CENTER_RADIUS,CENTER_RADIUS)).boundingRect().width() / CENTER_RADIUS;
```

**Comment by kaa-ching** [comment]
`theActionIconScaling` changes whenever the size of an object changes, which is **exactly** what it is *not* supposed to do - it should be constant across all objects within a scene as it is a scene parameter.

**Comment by kaa-ching** [comment]
Let's revisit this as part of the UI rewrite.

**Comment by kaa-ching** [comment]
pie menu gone. ticket no longer relevant.
