### ISSUE TITLE
Dragging an objects automatically centers it to cursor

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#197]
If you try to move an object by clicking and dragging it around, its center jumps immediately to the cursor.
I think this is really annoying and irritating for large objects since they basically “bounce” around, the object should just move with the cursor no matter where you clicked.

Tested in: 90d00d7a9ee69cbf03e1b278aeb1435ca5dc56d2

**Comment by kaa-ching** [comment]
yup, regression from adding the ObjectEditorDialog stuff. my bad.
