### ISSUE TITLE
Adding Link or PivotPoint object into editor makes TBE crash

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#198]
Here's a really obvious bug:
* Start editor
* Try to add Link or PivotPoint object
* Segmentation fault

Tested in: 90d00d7

**Comment by kaa-ching** [comment]
Interestingly, `TranslationGuide` works.
Also not working:
 * `Glue`

**Comment by kaa-ching** [comment]
Wuzzy, I think you are running a release build. Can you confirm that?

**Comment by Wuzzy2** [comment]
Sorry, my bad, I guess I have reported the bug incorrectly.
Here's what I get after running d38a61245d84ba3a2ed222335c4cf1c4e519bb42:

Adding a `Link`:
```tbe: /home/wuzzy/src/tbe/tbe/src/model/Link.cpp:173: virtual void Link::updateViewObject(bool) const: Assertion `false' failed.```

Adding a `PivotPoint`:
```ASSERT: "myVOPtr!=nullptr" in file /home/wuzzy/src/tbe/tbe/src/control/InsertUndoCommand.cpp, line 104```

Adding a `Glue` does not make TBE crash for me.

**Comment by kaa-ching** [comment]
Here's the current reason why `PivotPoint` crashes, which makes little sense:
```
    /// Overridden from AbstractObject/AbstractJoint: never create ViewObject.
    ViewObjectPtr createViewObject(float) override
    {
        return ViewObjectPtr(nullptr);
    }
```

Inserting a `Link` crashes for an entirely different reason.

Inserting a `TranslationGuide` works.

I'm going to make PivotPoint behave the same as TranslationGuide: allow to insert and set image to not found.

**Comment by kaa-ching** [comment]
`Link` crashes because of this:
```
#4  0x00000000004f550e in QList<std::shared_ptr<AbstractObject> >::first() (this=0x7fffffffc260) at /usr/include/qt5/QtCore/qlist.h:316
#5  0x00000000004f48c2 in PropertyList::property2ObjectPlusVectorPtr(World*, QString const&, Vector**) (this=0xf5f240, aWPtr=0xd260b0, aPropertyName=..., aVectorPtrPtr=0xf5f358) at /src/model/Property.cpp:216
#6  0x00000000004e9648 in Link::parseProperties() (this=0xf5f210) at /src/model/Link.cpp:155
#7  0x00000000005019f7 in World::addObject(std::shared_ptr<AbstractObject>) (this=0xd260b0, anObjectPtr=...)
    at /src/model/World.cpp:130
#8  0x00000000004b918b in InsertUndoCommand::redo() (this=0xf63b30) at /src/control/InsertUndoCommand.cpp:140
#9  0x00007ffff736b3b8 in QUndoStack::push(QUndoCommand*) () at /usr/lib64/libQt5Widgets.so.5
```
Which is because we ask for the first element in an empty list. That's easy to make more robust, 6b1b28a does that. Then it crashes further down with an `assert(false);`.

**Comment by kaa-ching** [comment]
changeset 6062756 makes Link almost work in the Level Creator: you can now select a link, edit the properties. If a property changes, you'll have to reload the level to make it work, though.

**Comment by kaa-ching** [comment]
I cannot make PivotPoint work in the Level Creator because you cannot make it use a ViewObject. 
Hence commit  d3daa9e that disables PivotPoint from the insert list.

**Comment by kaa-ching** [comment]
Done.
