### ISSUE TITLE
templatize translations for levels

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#20]
(note: totally reworded intro)

We're going to approach i18n of levels differently:
  * @glixx's script extracts strings from the level XML and adds it to the `i18n/tbe_levels.pot`
  * [www.transifex.com](transifex) is used to translate all level strings
  * we add po files per language for the levels. Example name: `i18n/tbe_levels_nl.po` 
  * during the building process, the `po` files are converted to `mo` files
  * those are packaged and put in the right locations

Actions to be done in this ticket:
 * [x] add infrastructure to Cmake to work with gettext
 * [x] add gettext support to the windows builds
 * [x] package the `mo` files
 * [x] finish i18n support in the code
 * [x] make sure it also works on Windows
 * [ ] make sure it also works on MacOSX

**Comment by glixx** [comment]
The current progress.
Needs to change:
```diff
    # we don't need symbol >, which written with br
    sed -i 's|br>|br\&gt;|g' "$fname"
    # we don't need symbol >, which written with a
    sed -i 's|a>|a\&gt;|g' "$fname"
    # we don't need symbol >, which written with i
    sed -i 's|i>|i\&gt;|g' "$fname"
```
and levels dir will be templatized.

**Comment by glixx** [comment]
An alternative solution: to use PO/MO files directly instead of adding translations into xml files.
There is script for POT file creating, there are PO files from transifex. So if do not add translations into XML files, then less work, only to install PO or MO files and to add support to code.

**Comment by kaa-ching** [comment]
I agree that I want to use this as the way forward.
Now I only need to figure out how to work with those files.

**Comment by kaa-ching** [comment]
With commit 6887271, I have completed all code to make it work for `test/level-i18n`.

It contains all code to make _all_ translation mechanisms work.

@amarsman: can you please validate whether this works on MacOSX? I will check Windows operation. (But not today, because I already know that `libintl.h` is missing on my Windows system...)

**Comment by amarsman** [comment]
[ 71%] Building CXX object src/CMakeFiles/tbe.dir/model/BalloonCactus.cpp.o
.../src/loadsave/Translator.cpp:30:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^
1 error generated.

So it breaks the build on Mac OS X.

I see several suggestions on this:
1) disable translations for Mac OS X
2) sometimes re-installing helps
3) installing other libraries

Not sure yet what's the best way forward and not much time this weekend.

**Comment by kaa-ching** [comment]
libintl on MacOSX seems to have triggered more bug reports on the internet :unamused: 

Looks like you indeed have to install some missing packages - `libintl` and maybe `libiconv2`.

**Comment by kaa-ching** [comment]
Oh, and sorry for _again_ breaking everything for you.

**Comment by kaa-ching** [comment]
@amarsman: you fixed this, didn't you?
Can you close if you did or specify what's left to do?

**Comment by amarsman** [comment]
This is fixed, verified that:
LANG=nl <tbe>
works.

**Comment by kaa-ching** [comment]
yay.
