### ISSUE TITLE
Less annoying simulation controls

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#200]
I think the simulation controls are still a bit annoying and inconvenient to use.

The following annoyances exist:

* You can not reset the simulation anymore while it was running. Why has this been disabled? It was really useful. Now the user is forced to do an additional state transition. Really annoying and I don't see a good reason for disabling it. But it is perfectly reasonable to go directly back to editing while it plays. If its done for technical reaons, TBE could simple do the additional step of going into pause mode first before switching to “stop” mode (the mode for adding objects and stuff) internally
* You can click on play and fast forwards when these modes are already active. But you can not do the same while in “stop” mode . That's pretty inconsistent, I think the button for the active mode should always be off, since there is no use for it.
* Using the simulation controls, you can't go back to start once you have reached the solved or failure state
* In general, allow sensible state transitions and disable the nonsensical ones. ;-)

Here's a list of suggested state transitions to give you a better understanding on what I actually want:

* Stop
	→ play
	→ FF (fast forward)
	→ RFF (really fast forward)

* Play
	→ stop (reset)
	→ pause
	→ FF
	→ RFF

* Pause
	→ stop
	→ play
	→ FF
	→ RFF

* FF
	→ stop
	→ pause
	→ play
	→ RFF
	
* RFF
	→ stop
	→ pause
	→ play
	→ FF
	
* Solved
	→ stop
	
* Failed
	→ stop

Other state transitions should not be possible.

**Comment by Wuzzy2** [comment]
Okay, with #227 being resolved, most of this issue is already fixed. The only thing which is missing is consistency.
The button for the current state should always be disabled, currently it is a bit inconsistent in this regard.

**Comment by kaa-ching** [comment]
I think we're done.
