### ISSUE TITLE
Missing guard rail image in level “Cola Reaction”

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#202]
The level “Cola Reaction” (`levels/draft/cola_reaction.xml`) is playable, but has poor/incomplete graphics. This can be confusing.
Namely, the silver peg in the middle is said to be set into a horizontal “guard rail” so it can only move horizontally. Technically, it is realized by using the `TranslationGuide` attribute. This is a very important part of the level, so it is not just about eye candy.

This level sould have a nice guard rail image as a scenery in the background so it looks more believable.
The “guard rail” may be as simple as a visual representation of the path the peg is “allowed” to move in. Ideally, it looks like the peg is physically inside of that thing.

**Comment by kaa-ching** [comment]
One approach could be to duplicate the graphics used in zoing-and-boom ?

**Comment by Wuzzy2** [comment]
Done in dd01d1edc5bf101155458df716dd636e23045ff5.
