### ISSUE TITLE
Level The maze is too easy

### ISSUE THREAD

**Issue by lspacenl** [the-butterfly-effect/tbe#204]
Due to the fact that the wedges are stuck to the scenery and don't fall down it's possible to solve this level by simply sticking a wedge directly under the starting position of the ball and let it run across the top of the maze. (see image)
![maze](https://cloud.githubusercontent.com/assets/16564496/14631727/18985e0c-0615-11e6-81de-286671193691.png)
This could be solved by adding a barrier to the top or widening the aperture or .......

**Comment by Wuzzy2** [comment]
Hehe, the level is supposed to be solved like this. :-)
If you know a solution where you only place wedges inside the maze, please report. Solutions of those kind are *not* intended.

**Comment by kaa-ching** [comment]
I know I did it with just triangles in the maze.
It's probably better to ensure it cannot work by making the triangles 10% bigger?

**Comment by Wuzzy2** [comment]
Screenshots, please. :-)
I don't want to make the wedges bigger, because it would become too obvious, then.

**Comment by lspacenl** [comment]
OK,
I did not realize this was intended, I thought it was a hack.
That also explains comments I heard before that this level was unsolvable.

But may I ask why?

**Comment by Wuzzy2** [comment]
The idea of this level is to think outside the box. ;-)

**Comment by kaa-ching** [comment]
:+1:

**Comment by lspacenl** [comment]
So mI guess this issue can be closed.
