### ISSUE TITLE
Revert traffic lights icon to stop icon

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#207]
I don't like the new traffic lights icon, since it is inconsistent with the other icons.

I have no real idea for a better icon, so I suggest to simply revert it to the old stop icon, at least that one is consistent with the other icons.

If we want a better set of icons, we should make sure they “fit” together and then we just put them into the game all at once for consistency. But we shouldn't do some half-hearted partial solution like this one.

**Comment by kaa-ching** [comment]
Agreed.
