### ISSUE TITLE
bad level Butterflies of doom

### ISSUE THREAD

**Issue by lspacenl** [the-butterfly-effect/tbe#211]
I think Butterflies of doom is broken.
When the hammer hits the bottom coke bottle it lacks the oomph to start the coke reaction. No amount of fine tuning seems to help, the bottle is just too far away and there is nothing you can insert to convey the energy.

**Comment by lspacenl** [comment]
![butterflies of doom](https://cloud.githubusercontent.com/assets/16564496/14760421/ad12c2d0-0943-11e6-9069-f010ee443b85.png)

**Comment by Wuzzy2** [comment]
The level is solvable, but the hammer section is indeed annoying to get right.
If the bowling ball is too slow, the hammer will be slowed down by the bowling ball.
The bowling ball has to kick the pin at the right speed, then it will work. But even then it is annoying to get right.
I try to tweak this level a bit.

PS: You can resize the floors.
