### ISSUE TITLE
Level “Domino Chest” is broken

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#215]
The level “Domino Chest” has become broken with the introduction of rotating bars. Because the rotating bar at the top left rotates around its center but it is not supposed to rotate around its center, but rather a corner.

@kaa-ching, can you please revert this level to the state it had before converting the birch bars to `RotatingBar`s? The original version had some birch bars where the pivot point was not in the middle, so those can logically not be replaced by a `RotatingBar`.

**Comment by kaa-ching** [comment]
done.
