### ISSUE TITLE
Use e.g. astyle to make the code layout consistent

### ISSUE THREAD

**Issue by amarsman** [the-butterfly-effect/tbe#218]
Currently there is no consistency in the code layout, e.g. a mix of tabs and spaces. Use a tool like Artistic Style: a Free, Fast, and Small Automatic Formatter for C, C++, C++/CLI, Objective‑C, C#, and Java Source Code. See [http://astyle.sourceforge.net](http://astyle.sourceforge.net).

1. make a proposal for the layout
2. discuss the proposal and get consensus
3. re-style all files in one go 
4. astyle can be used inside editors/IDEs, create instructions for the most common ones [http://doc.qt.io/qtcreator/creator-beautifier.html](http://doc.qt.io/qtcreator/creator-beautifier.html)

The QtCreator docs mentions:
1. Artistic Style
2. ClangFormat
3. Uncrustify

I've only used astyle, any experience with the other two @kaa-ching and @Wuzzy2?

astyle documentation: [http://astyle.sourceforge.net/astyle.html](http://astyle.sourceforge.net/astyle.html)
Any preferences @kaa-ching? I would like to use only spaces as a lot of other tools can't cope with a mix of tabs and spaces.

Which editor/IDE do you use @kaa-ching and @Wuzzy2? I use QtCreator and vim.

**Comment by Wuzzy2** [comment]
I use Vim.
I don't care about coding style and don't use tools for this.
But if TBE will adopt any coding style, I just adopt it as well.
I leave the decision on coding style issues to others.

**Comment by amarsman** [comment]
When I was looking at a file for a potential bug the code layout (indentation) using less was very unpleasant, looked like more was wrong than there was in practise.

**Comment by kaa-ching** [comment]
@amarsman : this issue is up next. 

Please create five pull requests - one per directory:
  * `src/*.{cpp|in}`
  * `src/control`
  * `src/loadsave`
  * `src/model`
  * `src/view`

Do not do anything on the Box2D directory, I'd like to keep Box2D as-is to make future merges of newer Box2D versions easier.

**Comment by kaa-ching** [comment]
I think that pull request #249 solves this issue.
