### ISSUE TITLE
Splash screen is probably not translated

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#221]
I am not sure about this issue, but it seems the splash screen is not translated.
The splash screen contains the message “Welcome to the Butterfly Effect!”. This message is always in English, no matter what I put in my .ts file.

Can you please investigate?

Tested in revision: 2c7ee9b70cc6ac425fd628561088f6e8533ded51

**Comment by kaa-ching** [comment]
Oops.
However, cannot be fixed for Milestone B anymore - "string freeze", remember?

**Comment by Wuzzy2** [comment]
The string seems to be already collected. I can see this string in the `.ts` file.

**Comment by amarsman** [comment]
Pull request created for the following commit:

commit 4e821587db84e23d9e93123c582b7b8b8c60daa7
Author: Aschwin Marsman <a.marsman@aynik.com>
Date:   Sun May 1 06:50:33 2016 +0200

    Fix: Splash screen is probably not translated #221
    The splash screen was shown before the translation is initialized.

**Comment by amarsman** [comment]
For me the splash screen is shown not long enough, it only flickers, you can't see what it is. Shouldn't it be shown at least e.g. a second?

**Comment by kaa-ching** [comment]
If you want to keep the splash screen longer, the trick it to delay the close event.
The splash is currently closed when the main window is initialised. You could change that to when the scene has been drawn (i.e. ViewWorld has been fully initialised). This will require some magic, though.

**Comment by amarsman** [comment]
I agree, nice to have, not part of this issue, this issue can be closed.

**Comment by kaa-ching** [comment]
Obviously, moving the splash screen until after the Qt infrastructure is initialised, doesn't help.

So, I think we'd better adjust it: first show the splash screen, then update the text after i18n is active.

**Comment by kaa-ching** [comment]
closing.
