### ISSUE TITLE
Cola splatter remains and TBE crashes afterwards

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#223]
See below screenshot, taken on Windows.
As you can see, the cola splatters don't remove themselves. After completing the level, TBE crashes.

![tbe-cola-splatter-remains](https://cloud.githubusercontent.com/assets/4249656/14943151/f68d9716-0fd1-11e6-8927-6396dbee0ba1.png)

**Comment by kaa-ching** [comment]
Same is true for explosion splatters:

![tbe-explosion-splatter-remains](https://cloud.githubusercontent.com/assets/4249656/14943200/e8214b36-0fd2-11e6-8406-6862f18527c3.png)

**Comment by kaa-ching** [comment]
Also happens on Linux now, must be related to one of the commits I did today.

**Comment by lspacenl** [comment]
This also explains my problem with boom boom boom, and that occurred last
Thursday. (sorry, cant connect to github on ny phone)
Op 1 mei 2016 7:22 PM schreef "Klaas van Gend" <notifications@github.com>:

**Comment by kaa-ching** [comment]
@lspacenl absolutely not related. I went back to commit c2e1d586eb7049bbc70959a01b5b0cfacbe15e82 (which predates last Thursday). 
There's nothing wrong with TBE in level Boom Boom Boom at that date that corresponds to this issue. The splatter disappears as usual.

**Comment by kaa-ching** [comment]
Indeed, at commit c2d1d58, "dial B for Boom" and "cola powered bike" do not exhibit the behavior that cola splatters or explosion splatters stay around.

**Comment by kaa-ching** [comment]
This is the culprit:
```
diff --git a/src/model/AbstractObject.cpp b/src/model/AbstractObject.cpp
index f7e737d..030d9e1 100644
--- a/src/model/AbstractObject.cpp
+++ b/src/model/AbstractObject.cpp
@@ -196,10 +196,8 @@ void AbstractObject::deletePhysicsObject()
 
 void AbstractObject::deleteViewObject(void)
 {
-       // delete the corresponding ViewObject
-       // note that delete nullptr is allowed
-       delete theViewObjectPtr;
-       theViewObjectPtr = nullptr;
+    // clear the corresponding ViewObject
+    theViewObjectPtr.clear();
 }
```
Reverting this patch solves this issue. 

However, this patch was made to solve #195. So I have work to do.

**Comment by kaa-ching** [comment]
There's a few side-issues left to address, like a few crashes :smiley: 
That's why I don't claim this is resolved yet.

**Comment by kaa-ching** [comment]
Issue #228 is now resolved and regression works for me. Closing this one as well.
