### ISSUE TITLE
TBE does not support dynamites with same ID / phone number

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#240]
The test level `DetonatorBoxDynamiteTest.xml` exposes a bug (IMO):

Both dynamites have the same phone number, but only the upper one gets triggered.

I think TBE should trigger _both_ dynamites if they share the same phone number. Because it would make for interesting level design, having one detonator box which could detonate two dynamites with a single press only.
Another issue this level shows that the dynamite phone number appears twice in the list of selectable phone numbers. Both of them only trigger the first dynamite.

Tested in: 96f6c7a68db601561c9026d9500df8cd68a07095

**Comment by kaa-ching** [comment]
One could argue that phone numbers in the world are unique. So you're asking for something that's not reality.
On the other hand, I think your suggestions make sense and no-one will even think twice about it. So I'm all for it. And it makes for some very interesting level mechanics.

It's not hard to do, I think.

**Comment by kaa-ching** [comment]
Done, regression passes.
