### ISSUE TITLE
Sane default Z-levels

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#246]
Some objects should have better default Z-levels which reflect the most common use case.

More precisely, I suggest the following new default Z-levels (assuming normal objects have a Z-level of 2):

* `Scenery` should have default Z-level of 0, usually you want those to have in the background
* `PingusExit`: 0.5 (see also #238)
* `Skyhook`: 1
* `PostIt`: 1.5
* `ToyChest`: 3
* `CardboardBox`: 4
* `Glue`: 5

After updating the default Z-level of anything, all levels should be checked if they still are graphically correct. This will be especially important for Scenery.
Explicitly stated Z-levels for PingusExit, PostIt, ToyChest and CardboardBox can generally be removed as redundant.

Feel free to suggest different Z-values if you disagree.

**Comment by kaa-ching** [comment]
I think Scenery default should be 0.1 - not zero.

**Comment by Wuzzy2** [comment]
I don't know why 0.1 instead of 0, but I'm fine with that.

**Comment by kaa-ching** [comment]
I'd suggest 0.1 because that means it's still possible to put things behind it.

**Comment by kaa-ching** [comment]
That's how it's easiest done. Set the default value as a default property. 
It will only be saved if it's not default. 

This approach should work for all objects that have a constructor, i.e. all of them :smile: .

**Comment by kaa-ching** [comment]
Link: default ZValue will be 6.0.

**Comment by kaa-ching** [comment]
Done.

**Comment by Wuzzy2** [comment]
No, not done. The second part of this issue is to go through all levels and update the scenery Z-level where it is inappropriate. Hopefully I find some time to do it later.

**Comment by Wuzzy2** [comment]
Okay, now it is done with d7a249ce08998a75812204fb9d5dc988be49d07a.
