### ISSUE TITLE
PivotPoint object is broken

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#263]
Issues with `PivotPoint` object right now:

* Existing levels now have a missing image for every `PivotPoint`
* If you start a level with a `PivotPoint` inside, TBE crashes

Tested in: 6b1b28a876860a120341522e76900ce3b3fe76f9

**Comment by kaa-ching** [comment]
I was still working on issue #198 !!!

**Comment by Wuzzy2** [comment]
Hahahhaha, sorry, it seems I am a bit to reckless in reporting lately. :-)

**Comment by kaa-ching** [comment]
Done, issue #198 is also done :smile:
