### ISSUE TITLE
Object names in toolbox appear cropped

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#278]
The toolbox is not really nice to look at in my opinion.

The actual issue I have with the toolbox is that the object names are sometimes cropped which looks very ugly. This happens more likely with long words.
I think this can't be fixed easily unless we do a redesign of the toolbox itself. I have the following ideas to solve this:

* 1: Remove object name from the toolbox itself so only the images remain. The object name is still shown if you clicked on one. This is the simplest solution.
* 2: Make toolbox width user-adjustable with a “grabber” of some sort
* 3: Move entire toolbox to the bottom instead of the right side, giving more than enough horizontal space for text. I am unsure how the images and text should be aligned.
* 4: Make the user decide whether to show images-only, text-only or both. However, if the user wants to show text, there's still the issue that the text might be cropped. So this solution should be combined with solution 2 (making width adjustable)

Please give your own opinion. :-)

**Comment by kaa-ching** [comment]
Nope. No longer the case in the new toolbox :smiley:
