### ISSUE TITLE
upload new strings to transifex

### ISSUE THREAD

**Issue by lspacenl** [the-butterfly-effect/tbe#302]
I see a lot of new post it notes and notes that remain in English but in Transifex translation sits at 100%.
Either some strings have not een declared as such or they have not been uploaded yet.

**Comment by Wuzzy2** [comment]
IMO updating strings regularily is not *that* important if no release is imminent. The strings will obviously change a lot if we come closer to the next release, so most translation work done now is likely to be tweaked or redone if the release comes close. Having a complete translation shortly before release is much more important than having a complete translation in the middle of development.

Maybe strings could be updated irregularily at low intervals in development phase so the project doesn't look entirely “dead” from Transifex. But I don't think this is important now and personally, I don't care much.

**Comment by kaa-ching** [comment]
At this point, it maybe makes sense to do a string update for the levels, but definitely not for the UI - many things will look differently in a month from now. I'll generate and update the levels thingie.

**Comment by kaa-ching** [comment]
At this point, it maybe makes sense to do a string update for the levels, but definitely not for the UI - many things will look differently in a month from now. I'll generate and update the levels thingie.

**Comment by kaa-ching** [comment]
As expected, all @Wuzzy2 's changed have created carnage in the levels POT file.
Oh well, at least most of the changes are now done.

**Comment by Wuzzy2** [comment]
Yes, but this was a neccessary as part of the badly needed project for quality assurance. I don't feel sorry. :)
