### ISSUE TITLE
Balloons go up! circumvented

### ISSUE THREAD

**Issue by torso** [the-butterfly-effect/tbe#303]
Placing the floor below left of the left volley ball will make it start rolling.

**Comment by Wuzzy2** [comment]
Not actually an issue of the level itself, but with the way the game allows to place objects.
IMO objects should not be allowed to be placed in a way that kinda push other objects since they end of slightly “inside” them.

As such, this is an duplicate of #131.

**Comment by torso** [comment]
Didn't look like it penetrated the ball. It was more about taking advantage of the ball falling slightly.

This technique also works in Float, balloon, float!

**Comment by lspacenl** [comment]
If that's true then the ball was not placed correctly, unless its intended and I don't believe that.
