### ISSUE TITLE
Strange black lines in Petanque level

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#305]
In the Petanque level (picnic level), there are several strange black lines at the jointed objects, namely the arm of the petanque player and the birch wood.

f9acb9c1df649b0bc8719fa17892f8decefb5ffa

I am not sure if this is an issue with this level only or an issue of the game itself. In any case, this is an UI issue.

**Comment by kaa-ching** [comment]
My bad. This is due to a change in how the Link object handles colour.

**Comment by Wuzzy2** [comment]
Sorry, I still see a black line at the birch wood to the right.
