### ISSUE TITLE
shift+f mode

### ISSUE THREAD

**Issue by glixx** [the-butterfly-effect/tbe#327]
Need to add in menu "Controls" this mode and add button.
It's only shortcut right now.

**Comment by kaa-ching** [comment]
shift-f is "super fast forward".
I don't want to add a button for it - it would clutter the interface.

**Comment by Wuzzy2** [comment]
Yeah, it's not really needed. Shortcut is enough. As long it's documented in the help (it is), it's OK.
I recommend closure.
