### ISSUE TITLE
Bad levels

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#34]
Current levels that do not behave:

* [x] **Jumping Around I**: 
1) there's no logic to where the volleyball should be placed. 
2) there is no fail, the 'skip' button is thus not easy to find.

* [x] **Tent** (picnic-0):
1) there's no post-it. Really important, because it is the first level where rotation is possible.

* [x] **Bowling Pin plays soccer**:
  1) the chicken wire is too coarse, the tennis ball can be put through.

* [x] **Balloons do poof**:
1) not reliable enough: the bowling ball often gets stuck.

* [x] **Party at the office**:
1) not reliable enough: the cola bottle doesn't always rotate fully.

* [x] **Poing Poing Poing**:
Many issues with this level, but it is solvable. however, the right pin's support needs to be smaller, so it drops easier. Also lower the bottle to make it easier to blow the pin.

* [x] **Loopings**:
Level is not reliable enough: dropping the bottle anywhere near the left should work.

* [x] **Springboard**:
Doesn't work anymore?

* [x] **Bridge the gap III**:
The fact that both the pin must topple an the (very bouncy) tennis ball must cross, makes this level too annoying. _Resolved by removing the level_

* [x] **Hole-in-one**:
 1) Doesn't work anymore, the bowling ball gets stuck outside of user's intervention.
 2) No Post-it note.

* [x] **Domino day**:
Bottom blue stone doesn't topple.

* [x] **Butterfly on steriods**:
Butterlfy doesn't fly high enough.

* [x] **Loopings2**:
Soccer ball doesn't roll past the curve.

* [x] **Zoing-and-boom**:
 1) Determinism in level is gone: the second explosion vs the domino stone 
 2) the soccer ball doesn't have enough momentum to reach the pin.

* [x] **Find the Message**: 
 1) Detonator box doesn't get triggered by ball. 
 2) Needs fail: butterfly hitting the flower istead of butterfly just flying through like it does now.

* [x] **Coconut instead of Cola**:
  1) you can place the cola crate above the palm by rotating it in a clever way. The game allows you to place objects partly “outside” of the field.

* [x] **Contraption 2**:
  1) can be solved stupidly easy by just playing a bowling pin just above the goal bowling pin to push it into the hole.

**Comment by kaa-ching** [comment]
zoing-and-boom still to be fixed.

**Comment by kaa-ching** [comment]
`zoingandboom.xml` and `springboard.xml` still to be fixed.

**Comment by kaa-ching** [comment]
Note that none of the picnic's have post-its...

**Comment by kaa-ching** [comment]
Took the lazy way out: commented out the nonfunctional levels and added three replacements.
Total is still 45.
Moving fixing to milestone B.

**Comment by glixx** [comment]
Springboard is fully workable for me.

**Comment by glixx** [comment]
* <b>Coconut instead of Cola</b>:

I'm not sure it should be won. If to put Cola Crate or Wooden bar over coconut.
![tbe6](https://cloud.githubusercontent.com/assets/2681872/9980849/cd4000a0-5fb0-11e5-8691-a1e489492104.png)

**Comment by kaa-ching** [comment]
I don't want to loose the level that honors Ruud Derwig, chair of the Embedded Linux Conference Europe in 2009 :-). Commit 169758d almost resolves the coconut issue by adding another leave to the tree, issue 203c114 solves it completely.

**Comment by Wuzzy2** [comment]
Sorry, but the level “Coconut instead of Cola” level can still be solved in a similar way as said above as you can still place the cola crate above the palm by rotating it in a clever way. The game allows you to place objects partly “outside” of the field.

**Comment by Wuzzy2** [comment]
Contraption 2 can be solved stupidly easy by just playing a bowling pin just above the goal bowling pin to push it into the hole.

**Comment by kaa-ching** [comment]
9e5a713 resolves Wuzzy2's problems with Contraption2, I hope :wink:

**Comment by Wuzzy2** [comment]
* Bridge the Gap II: Looks like a RectObject without image snuck its way into the level and it is placed in a very weird position *on* the bowling ball.

**Comment by Wuzzy2** [comment]
There are two currently two slightly different levels called “My brother likes soccer”.

**Comment by kaa-ching** [comment]
![butterfly-on-steroids-wrong](https://cloud.githubusercontent.com/assets/4249656/12694947/fc26d962-c73d-11e5-9403-15fda1650998.png) Good catch on the butterfly-on-steroids level, @Wuzzy2

**Comment by Wuzzy2** [comment]
Why is Loopings 2 in this list? I have no problems solving this level, and the soccer ball does not get stuck in any curve.

**Comment by kaa-ching** [comment]
I took out the original loopings and the springboard levels. Loopings2 doesn't have problems as far as i know... I haven't witnessed what @glixx wrote above.

**Comment by kaa-ching** [comment]
So that leaves fixing "zoing and boom" - one of my more complex levels, and unfortunately not really deterministic :unamused:

**Comment by Wuzzy2** [comment]
* Extreme Tux Racer doesn't seem to work anymore (as intended?). The soccer ball does not seem to have enough energy to go to the bowling ball. Unless I place it directly above the bowling ball (but this does not seem to be the intended solution).

**Comment by kaa-ching** [comment]
done.

**Comment by kaa-ching** [comment]
further notes on bad levels should go into a new ticket.
