### ISSUE TITLE
Remove install instructions from wiki

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#350]
I have recently copied the advanced install instructions from the wiki to the main repo.

In generally, install instructions should be in the repo because that way, it will be available offline as well.

Generally, we should not have critical knowledge for users and package builders exclusive in the wiki.

I propose to remove the build instructions from the wiki as redundant now (instead link to repo). Do you agree?

**Comment by kaa-ching** [comment]
I think there's a difference between the stuff that everyone should know about and what *some* developers need to know about. 

So, yes: up to package builders should be in the repo. Stuff for maintainers (? I don't think we have that) should not.

Please remove what is double.

**Comment by Wuzzy2** [comment]
OK, done. MacOS build and Window build instructions removed from wiki.
