### ISSUE TITLE
Simplify level licensing / replace “Public Domain” with all-permissive license

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#355]
Current level licenses are a bit all over the place.

I suggest to simplify the licenses to use less different licenses overall.

I suggest to at least unify the all-permissive licenses such as MIT, WTFPL, BSD. Also, “Public Domain” / “PD” is not a license and should be turned into one.

I do not want to touch any other licenses it it's probably too complicated and probably not possible anyway.

I suggest to switch all levels with an all-permissive license to CC0 <https://creativecommons.org/publicdomain/zero/1.0/>, as it's probably best for media.

After doing this, it also needs to be checked if any README and similar files need updating.

I don't want to do this step on my own and first seek for approval of the other project members.

**Comment by kaa-ching** [comment]
approved for my levels.

**Comment by Wuzzy2** [comment]
Done.
da4afa12cdfe5edca0792794dc8a25a0e8d5e981
