### ISSUE TITLE
CentOS: installation issues

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#48]
Trying to install tbe-0.9.2.1.rpm and .sh:

CentOS 6:
 * rpm fails: glibc wrong version, `libqt4-x11` package doesn't exist
 * self-extracting archive fails to execute: wrong versions of `glibc` and `libstdc++`

CentOS 7:
 * rpm fails: `libqt4-x11` package doesn't exist
 * rpm install with --nodeps: package installs, icon doesn't appear in menu.
 * self-extracting archive works

**Comment by glixx** [comment]
You create RPM and DEB packages wrong absolutely. You will never create workable packages using your way.
If you want to add tbe to any distribution you should go there with new package request.

**Comment by glixx** [comment]
http://pkgs.org/search/thebutterflyeffect
ALT Linux, Fedora, Mageia have tbe in repo. They will update your packages after me if you publish correct release https://github.com/kaa-ching/tbe/issues/46 . You released without my opinion about tbe is ready for release or not, did not care for translations. Needs more polish before packaging.
Anyway packaging for linux is maintainer's work.

**Comment by kaa-ching** [comment]
I wasn't aware of ALT and Fedora :smiley: 
I will rebuild the rpm packages for Opensuse and CentOS and Ubuntu on Saturday and validate the workings. Looks like I'll have some work to do. Note that me providing rpms and debs is a service - if it is in the repo, I'd like to point to the repo.

@glixx: do you have pointers or example text for installation instructions for Mageia?

**Comment by glixx** [comment]
For Mageia:
rpmdrake - graphical manager of packages
urpmi tbe - install from console (needs root permissions)
tbe will be available for Mageia 6

You only lose time for packaging. Anyway your packages will not be workable. You can use http://openbuildservice.org/ or better to work with maintainers directly.

**Comment by kaa-ching** [comment]
The RPM package doesn't work (on Opensuse, but probably also on Centos) because it's lacking the /usr directory in front of the tree - it installs in `/share` and `/games` . Sigh.

**Comment by glixx** [comment]
You only lose time for packaging. Package must be built in clean chroot environment and only for version of distro, from where clean chroot environment was used. Your packages never will be workable. Don't lose your time.
OBS allows to build packages for many distros.
tbe has no manual dependencies, they will be added automatically by rpmbuild/dpkg. Your lib* dependencies are wrong.

**Comment by kaa-ching** [comment]
Don't worry, you have convinced me. However, I don't want to learn fighting OBS. I've fought it once to work with Tizen, I'm not in the mood to do that again.

BTW: for the windows build, I have to change a few things, there will be a new tag 0.9.2.1 soonish. That might also contain a few MacOSX changes.

**Comment by kaa-ching** [comment]
The latest version of the tree, 7ad03f3, yields an RPM package that works smoothly in opensuse - at least if built in opensuse. As long as we don't have any OBS builds, I'm going to publish that one.
Same for the .deb: it works smoothly on Ubuntu if built on Ubuntu. I will update the documentation for that.
I'm dropping CentOS for now and hope that someone will indeed package 0.9.2.1 for Fedora.

**Comment by glixx** [comment]
tbe will be packaged for Fedora after Mageia when 0.9.2.1 tag will be available.
Will you change in spec:
%makeinstall_std on %make_install (new in rpm-4.13)?

**Comment by kaa-ching** [comment]
tag now available. Sorry, didn't see this message and need to leave now.
enjoy your packaging.

**Comment by glixx** [comment]
> icon doesn't appear in menu.

hicolor-icon-theme package helps?

**Comment by glixx** [comment]
http://pkgs.org/search//usr/share/applications/tbe.desktop
tbe-0.9.2.1 was packaged for Mageia and Fedora
They uses different prefixes for installation, but /usr/share/applications/tbe.desktop should be the same for all distros. So packages can be searched by http://pkgs.org using /usr/share/applications/tbe.desktop

**Comment by kaa-ching** [comment]
>> icon doesn't appear in menu.

> hicolor-icon-theme package helps?

No, it was much simpler: `/usr` prefix was missing. I can build CentOS packages if I rewrite the dependencies on packages: the libqt package is named differently. Don't have time for that now, though.
I'll add your builds on pkgs.org to the website.

**Comment by kaa-ching** [comment]
Somehow I expect this issue to be solved, due to the ability to override all installation paths when calling cmake.
