### ISSUE TITLE
Add path options for cmake

### ISSUE THREAD

**Issue by glixx** [the-butterfly-effect/tbe#49]
Needs to add cmake options for gamesbindir, gamesdatadir.
Maintainers of Fedora, Arch Linux do not like the current implementation.

**Comment by kaa-ching** [comment]
I agree, would work better for the Windows and self-extracting archive packages, too.

The current directory set appears to be just fine for Ubuntu and Mageia.

The variables are already defined in the CMakeLists.txt file, so:
 * [ ] we need a mechanism to overrule the set variables or at least differentiate
 * [ ] we need a mechanism to make sure that TBE knows more about the file locations, i.e. generate `tbe_paths.h` from the settings.
 * [ ] we need to know what the various paths for the various distros look like.

**Comment by kaa-ching** [comment]
@glixx: can you help to figure out what the Fedora and ALT packagers want for a directory layout?

**Comment by glixx** [comment]
For Mageia, Debian, Alt Linux:
gamesbindir=/usr/games
gamesdatadir=/usr/share/games

For Fedora, Arch Linux:
gamesbindir=/usr/bin
gamesdatadir=/usr/share

**Comment by kaa-ching** [comment]
@glixx: thanks for the info, this will be enough to make it work.

**Comment by kaa-ching** [comment]
I expect this issue to be closed because we can now adjust the installation paths to all directories during package build.
