### ISSUE TITLE
Partial localization under wine

### ISSUE THREAD

**Issue by glixx** [the-butterfly-effect/tbe#61]
If to install tbe under wine in linux, then localization is not full.

**Comment by amarsman** [comment]
Why would you use wine on Linux? Do you want to test the Windows build without access to Windows?

**Comment by glixx** [comment]
If somebody has no packages for linux or cannot install tbe in linux, but has thebutterflyeffect-*-win32.exe and wine, then tbe works under wine, but needs to fix localization.

**Comment by kaa-ching** [comment]
I'm happy to hear that it works on Wine - I personally hadn't checked nor considered it as a use case.

I'm also surprised to see that the Wine version doesn't have full localization - I verified that to work before I built the final packages.

@glixx : can you please update your initial post with what works and what doesn't work?

**Comment by glixx** [comment]
Installer: works fine, localization is OK
Uninstaller: works fine, localization is OK
tbe: I see localization only from xml files, qt is not localized fully (qm files from qt were not packaged), ui is not localized fully (tbe does not use qm files).

**Comment by kaa-ching** [comment]
Thanks, @glixx !

**Comment by glixx** [comment]
ui is not localized fully (tbe does not use qm files)
