### ISSUE TITLE
Game crashes when attempting to start level with no level selected and all levels 'done' or 'skipped'.

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#80]
If you start the game and have finished all levels in the list, the level selection comes up, but no level is selected. Not a problem, until you press “Go!”. Boom, the game explodes with a critial error:

> ERROR during reading file '': ' Cannot read file '''

Only tested in 0.9.2.1, because I did not bother to finish all levels again in the dev version. xD

**Comment by kaa-ching** [comment]
If you want to test it in the dev version, do the following:
 1. complete at least one level
 1. open up `~/.config/the-butterfly-effect.org/The Butterfly Effect.conf`
 1. edit the config file by copying all names appropriately
 1. save
 1. try again. If properly done, it should now list all levels as 'done'.

**Comment by Wuzzy2** [comment]
Reproduced successfully in ceadc7e6223ffd680e2c731bb51e7bddb6500267..

**Comment by Wuzzy2** [comment]
Maybe just make sure TBE always starts with some default level in cases like this?
The “no level loaded” state is really strange and buggy anyways and it would be no big loss.

**Comment by Wuzzy2** [comment]
Fixed a long time ago by #137.
